## Operadores - gestiÃ³n de errores

Ejemplo **catchError**: Podemos interceptar cualquier error emitido, y devolver otro observable(somo si no pasara nada).
```ts
const sec = rxjs.throwError("ðŸ‘¿");

sec.pipe(
  rxjs.operators.catchError(err => {
    return rxjs.of(`ðŸ˜‡ => ${err}`)
  })
).subscribe(
  next: (value) => console.log("VALUE", value), //  ðŸ˜‡ => ðŸ‘¿
  error: (err) => console.log("ERROR", err) // ERROR ðŸ‘¿
})
```